@startuml

package Exporter {}
package Configuration {}
package Specification {}
package Island {}
package MeshADT {}
package JTS LightSalmon {}
package "Apache CLI" LightSalmon {}
package io LightBlue {}
package Geography {}
package Features {}

class Main


Main .> Specification
Configuration <. Main
Configuration <. Specification

Main ..> Exporter
Exporter ..> MeshADT
Specification ..> Island
Exporter .> Island
Exporter ..> io

Island .> JTS
Configuration ..> "Apache CLI"
Exporter ..> Geography

Specification .> Features
Features ..> Island
Features ..> Geography
Features ..> MeshADT
Features ..> JTS


@enduml